/* eslint-disable max-len */
export const profileViewServiceResponse = {
    default: {
        data:
         [{
             type: 'profileView',
             id: 'a76c652e-c016-4dbf-9e77-1225db91f5ff',
             viewDate: '2022-03-31T10:09:53+02:00',
             company: {
                 type: 'company',
                 d: '116612',
                 name: 'Einhorn GmbH & Co. KG',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 4,
                 logo: 'https://static.karriere.dev:443/company/116612/3533795/out.companysmall.png',
                 logoSquare: 'https://static.karriere.dev:443/company/116612/3533795/out.companysquare.png',
                 image: null,
                 slug: null,
                 locations: 'Linz',
                 branches: 'Land-, Forstwirtschaft, Logistik, Transport',
                 profileUrl: '/f/einhorn-gmbh',
                 jobsUrl: '/f/einhorn-gmbh#jobs',
             },
         }, {
             type: 'profileView',
             id: '90ac1861-b259-48df-924e-fed8db63b392',
             viewDate: '2022-03-12T13:06:53+01:00',
             company: {
                 type: 'company',
                 id: '115627',
                 name: 'Performas GmbH',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 2,
                 logo: 'https://static.karriere.dev:443/company/115627/3418418/p.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/115627/3418418/p.companysquare.gif',
                 image: 'https://static.karriere.dev:443/company-profile/115627/3417917/foyer.thumb.jpg',
                 slug: null,
                 locations: 'Linz',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/performas',
                 jobsUrl: '/f/performas#jobs',
             },
         }, {
             type: 'profileView',
             id: 'b96f3797-b69c-4832-a700-8c97bdc76838',
             viewDate: '2022-03-09T08:56:46+01:00',
             company: {
                 type: 'company',
                 id: '52775',
                 name: 'Pavelka-Denk Personalberatung',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 15,
                 logo: 'https://static.karriere.dev:443/company/52775/1865528/logo.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/52775/1865528/logo.companysquare.gif',
                 image: 'https://static.karriere.dev:443/company-profile/52775/3209236/567fete_excel17_572-1024x683.thumb.jpg',
                 slug: null,
                 locations: 'Wien',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/pavelka-denk-personalberatung',
                 jobsUrl: '/f/pavelka-denk-personalberatung#jobs',
             },
         }, {
             type: 'profileView',
             id: '81b0f259-ad80-4b2e-ba33-e3409a7b47f5',
             viewDate: '2022-03-03T07:04:30+01:00',
             company: {
                 type: 'company',
                 id: '64',
                 name: 'epunkt GmbH',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 1008,
                 logo: 'https://static.karriere.dev:443/company/64/1538013/logo-epunkt-internet-recruiting.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/64/1538013/logo-epunkt-internet-recruiting.companysquare.gif',
                 image: 'https://static.karriere.dev:443/company-profile/64/3482198/ep_mediumres_20.thumb.jpg',
                 slug: null,
                 locations: 'Linz, Wien, Graz, Salzburg',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/epunkt-linz',
                 jobsUrl: '/f/epunkt-linz#jobs',
             },
         }, {
             type: 'profileView',
             id: 'c3b8f9de-bdca-4e55-b7aa-4ce473006732',
             viewDate: '2018-08-08T09:23:01+02:00',
             company: {
                 type: 'company',
                 id: '58',
                 name: 'Schulmeister Finance',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 200,
                 logo: 'https://static.karriere.dev:443/company/58/3191385/schulmeister-finance.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/58/3191385/schulmeister-finance.companysquare.gif',
                 image: null,
                 slug: null,
                 locations: 'Wien, Linz, Graz',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/schulmeister-finance',
                 jobsUrl: '/f/schulmeister-finance#jobs',
             },
         }, {
             type: 'profileView',
             id: 'aa89d107-54ae-4813-8d24-71ea5e1381f8',
             viewDate: '2018-06-27T13:17:51+02:00',
             company: {
                 type: 'company',
                 id: '136',
                 name: 'karriere.at',
                 isActive: true,
                 isChiffre: false,
                 typeId: 2,
                 typeLabel: 'BRANDING_SOLUTION',
                 activeJobs: 15,
                 logo: 'https://static.karriere.dev:443/company/136/3342462/logo-gross.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/136/3342462/logo-gross.companysquare.gif',
                 image: '//kcdn.at/video/84248/3577723/1-medium.jpg',
                 slug: null,
                 locations: 'Linz, Wien',
                 branches: 'Internet, IT, Telekom',
                 profileUrl: '/f/karriere-at',
                 jobsUrl: '/b/karriere-at#jobs',
             },
         }, {
             type: 'profileView',
             id: 'ed09bae0-7845-4943-96a7-fd23393e3a70',
             viewDate: '2018-03-26T13:54:32+02:00',
             company: {
                 type: 'company',
                 id: '52537',
                 name: 'best4best unternehmens- & personalentwicklung KG',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 5,
                 logo: 'https://static.karriere.dev:443/company/52537/3436696/b4b.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/52537/3436696/b4b.companysquare.gif',
                 image: null,
                 slug: null,
                 locations: 'Linz',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/best4best-unternehmens-personalentwicklung',
                 jobsUrl: '/f/best4best-unternehmens-personalentwicklung#jobs',
             },
         }, {
             type: 'profileView',
             id: '778dbcd7-560b-4191-9376-8a8e0bf459b4',
             viewDate: '2017-10-17T15:46:08+02:00',
             company: {
                 type: 'company',
                 id: '54168',
                 name: 'eXperts consulting center',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 39,
                 logo: 'https://static.karriere.dev:443/company/54168/3353214/experts_logo_18.companysmall.jpg',
                 logoSquare: 'https://static.karriere.dev:443/company/54168/3353214/experts_logo_18.companysquare.jpg',
                 image: 'https://static.karriere.dev:443/company-profile/54168/3353217/header_fuerbewerber.thumb.jpg',
                 slug: null,
                 locations: 'St. Florian, Wien, Graz',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/experts-consulting-center',
                 jobsUrl: '/f/experts-consulting-center#jobs',
             },
         }, {
             type: 'profileView',
             id: '6a6aa4e4-cd96-4ab1-9f7d-9f0e4ebc0c01',
             viewDate: '2017-10-17T15:35:27+02:00',
             company: {
                 type: 'company',
                 id: '79',
                 name: 'ISG Personalmanagement GmbH',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 439,
                 logo: 'https://static.karriere.dev:443/company/79/3467946/isg_logo.companysmall.jpg',
                 logoSquare: 'https://static.karriere.dev:443/company/79/3467946/isg_logo.companysquare.jpg',
                 image: 'https://static.karriere.dev:443/company-profile/79/3195800/karlskirche3.thumb.jpg',
                 slug: null,
                 locations: 'Wien',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/isg-personalmanagement',
                 jobsUrl: '/f/isg-personalmanagement#jobs',
             },
         }, {
             type: 'profileView',
             id: 'd536a754-be12-4df1-a928-d38f6e586b7b',
             viewDate: '2017-10-11T13:13:16+02:00',
             company: {
                 type: 'company',
                 id: '15920',
                 name: 'PMC International GmbH',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 112,
                 logo: 'https://static.karriere.dev:443/company/15920/376066/logo-pmc-international-gmbh.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/15920/376066/logo-pmc-international-gmbh.companysquare.gif',
                 image: null,
                 slug: null,
                 locations: 'Wien',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/pmc-international',
                 jobsUrl: '/f/pmc-international#jobs',
             },
         }, {
             type: 'profileView',
             id: 'c9a3cdbe-5f1d-4a48-9760-be47d6bb8b02',
             viewDate: '2017-08-24T15:20:07+02:00',
             company: {
                 type: 'company',
                 id: '50647',
                 name: 'eMagnetix - Online Marketing GmbH',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 0,
                 logo: 'https://static.karriere.dev:443/company/50647/3281067/logo_karriereat.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/50647/3281067/logo_karriereat.companysquare.gif',
                 image: 'https://static.karriere.dev:443/company-profile/50647/3537607/foto_karriere1.thumb.jpg',
                 slug: null,
                 locations: 'Bad Leonfelden',
                 branches: 'Werbung, Marketing, PR',
                 profileUrl: '/f/emagnetix-online-marketing',
                 jobsUrl: '/f/emagnetix-online-marketing#jobs',
             },
         }, {
             type: 'profileView',
             id: 'd3dfc7e4-ffc6-4ea0-8012-a02846b15ab3',
             viewDate: '2017-08-22T15:19:11+02:00',
             company: {
                 type: 'company',
                 id: '50818',
                 name: 'Randstad Personalberatung',
                 isActive: true,
                 isChiffre: false,
                 typeId: 0,
                 typeLabel: 'EMPLOYER_PAGE',
                 activeJobs: 7,
                 logo: 'https://static.karriere.dev:443/company/50818/501022/logo-randstad-personalberatung.companysmall.gif',
                 logoSquare: 'https://static.karriere.dev:443/company/50818/501022/logo-randstad-personalberatung.companysquare.gif',
                 image: null,
                 slug: null,
                 locations: 'Wien',
                 branches: 'Personaldienstleistung',
                 profileUrl: '/f/randstad-personalberatung',
                 jobsUrl: '/f/randstad-personalberatung#jobs',
             },
         }],
        meta: {
            pagination: {
                number: 1,
                size: 12,
                total: 23,
                pages: 2,
            },
        },
    },
    noProfileViews: {
        data: [],
        meta: {
            pagination: {
                number: 1,
                size: 12,
                total: 0,
                pages: 0,
            },
        },
    },
    noPagination: {
        data: [
            {
                id: 'profileView-1',
                viewDate: '2020-07-22T00:57:58+02:00',
                company: {
                    type: 'company',
                    id: 'company-1',
                    name: null,
                    isActive: false,
                    isChiffre: false,
                    typeId: null,
                    typeLabel: 'EMPLOYER_PAGE_PLUS',
                    activeJobs: 4,
                    logos: null,
                    image: null,
                    slug: null,
                    locations: null,
                    branches: null,
                    profileUrl: null,
                    jobsUrl: null,
                },
            },
        ],
        meta: {
            pagination: {
                number: 1,
                pages: 1,
                size: 0,
                total: 1,
            },
        },
    },
};
